spring.application.name=universidad-api
server.port=${SERVER_PORT:8081}
spring.profiles.default=dev
debug=false
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
